# Generated by Django 3.2.8 on 2021-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
