# Generated by Django 3.2.8 on 2021-10-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due_premium_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
