version: "3"

services:
  db:
    image: postgres:13.4
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    container_name: threadly_api
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-file /code/logs/gunicorn-error.log
    volumes:
#      - .:/code
      - ./data/static:/code/static/
      - ./data/logs:/code/logs
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  redis:
    image: redis:6.2.6
    ports:
      - 6379
  celery-task:
    build:
      context: .
    restart: always
    command: celery -A config worker -l INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
  celery-scheduler:
    build:
      context: .
    restart: always
    command: celery -A config beat -l INFO -S django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
      - celery-task
