version: "3"

services:
  db:
    image: postgres:13.4
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: threadly_api
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --log-file /code/logs/gunicorn-error.log
    volumes:
#      - .:/code
      - ./data/static:/code/static/
      - ./data/logs:/code/logs
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
