# Generated by Django 3.2.8 on 2021-10-29 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 23, 30, 55, 940116, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
